---
# Default configuration for mdp-dedupe

# Path configurations
paths:
  # Directory for processed data files
  processed_data: "data/processed"
  # Directory for model files
  models: "data/models"
  # Directory for results output
  results: "data/results"

# Database configuration
database:
  # PostgreSQL connection URL using environment variables
  url: "postgresql://${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
  echo: false

# Deduplication settings
dedupe:
  # Threshold for considering records as duplicates (0.0 to 1.0)
  threshold: 0.5
  # Fields used to determine what are matches
  fields:
    - name: "first_name"
      type: "String"
      has_missing: true
    - name: "last_name"
      type: "String"
      has_missing: true
    - name: "email"
      type: "String"
      has_missing: true
    - name: "phone_number"
      type: "String"
      has_missing: true
    - name: "address"
      type: "String"
      has_missing: true
    - name: "date_of_birth"
      type: "String"
      has_missing: true

# Field mappings for each data source
field_mappings:
  clinic:
    # We're using this as standard shape, just map to same names
    "first_name": "first_name"
    "last_name": "last_name"
    "phone_number": "phone_number"
    "date_of_birth": "date_of_birth"
    "email": "email"
    "address": "address"

  urgent_care:
    # Map variant field names to standard names
    "first_name": "first_name"
    "last_name": "last_name"
    "dob": "date_of_birth"
    "phone": "phone_number"
    "email": "email"
    "address_line": "address"

  hospital:
    # Map variant field names to standard names
    "first_name": "first_name"
    "last_name": "last_name"
    "date_of_birth": "date_of_birth"
    "phone_number": "phone_number"
    "email_address": "email"
    "address": "address"

  physical_therapy:
    # Map variant field names to standard names
    "dob": "date_of_birth"
    "contact_phone": "phone_number"
    "email": "email"
    "street_address": "address"
    "city": "city"
    "state": "state"
    "zip_code": "zip_code"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    file:
      enabled: true
      path: "logs/mdp_dedupe.log"
      max_bytes: 10485760 # 10MB
      backup_count: 5
